kind: pipeline
name: default


steps:
- name: publish docker  
  image: plugins/docker
  settings:
    repo: willianvalerio/dd-dotnet-todolist
    dockerfile: TodoApi/Dockerfile
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password: 
      from_secret: DOCKER_PASSWORD
  when:
    branch:
    - main
    - master